const c=document.getElementById("fx"),x=c.getContext("2d"),start=document.getElementById("start"),btn=document.getElementById("open"),msg=document.getElementById("message");let W,H,P=[],R=[],audio;
function size(){W=innerWidth;H=innerHeight;const d=Math.min(devicePixelRatio||1,2);c.width=W*d;c.height=H*d;c.style.width=W+"px";c.style.height=H+"px";x.setTransform(d,0,0,d,0,0)}addEventListener("resize",size);size();
class Particle{constructor(X,Y,a,s,h){this.x=X;this.y=Y;this.vx=Math.cos(a)*s;this.vy=Math.sin(a)*s;this.h=h;this.a=1}update(){this.vx*=.985;this.vy=this.vy*.985+.045;this.x+=this.vx;this.y+=this.vy;this.a-=.012}draw(){x.save();x.globalAlpha=Math.max(0,this.a);x.fillStyle=`hsl(${this.h},100%,65%)`;x.shadowBlur=12;x.shadowColor=x.fillStyle;x.beginPath();x.arc(this.x,this.y,1.5+Math.random()*1.5,0,7);x.fill();x.restore()}}
function burst(X,Y,n=100){let h=Math.random()*360;for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=2.5+Math.random()*5.5;P.push(new Particle(X,Y,a,s,(h+Math.random()*80)%360))}crackle()}
function rocket(X,Y,h){R.push({x:X,y:H+10,t:Y,v:-(8+Math.random()*2),h})}
function sound(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume()}
function crackle(){if(!audio)return;let sr=audio.sampleRate,L=sr*.45,b=audio.createBuffer(1,L,sr),d=b.getChannelData(0);for(let i=0;i<L;i++)d[i]=(Math.random()*2-1)*(1-i/L)**2;let s=audio.createBufferSource(),g=audio.createGain(),f=audio.createBiquadFilter();f.type="highpass";f.frequency.value=900;g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.22,audio.currentTime+.015);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.45);s.buffer=b;s.connect(f);f.connect(g);g.connect(audio.destination);s.start()}
function boom(){if(!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.frequency.setValueAtTime(120,audio.currentTime);o.frequency.exponentialRampToValueAtTime(42,audio.currentTime+.45);g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.45,audio.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.45);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.46)}
function loop(){x.fillStyle="rgba(0,0,0,.18)";x.fillRect(0,0,W,H);for(let i=R.length-1;i>=0;i--){let r=R[i];r.y+=r.v;r.v+=.045;x.fillStyle=`hsl(${r.h},100%,70%)`;x.shadowBlur=10;x.beginPath();x.arc(r.x,r.y,2.5,0,7);x.fill();if(r.y<=r.t||r.v>=-1){burst(r.x,r.y,100);R.splice(i,1)}}for(let i=P.length-1;i>=0;i--){P[i].update();P[i].draw();if(P[i].a<=0)P.splice(i,1)}if(R.length||P.length)requestAnimationFrame(loop)}
btn.onclick=()=>{sound();start.classList.add("hide");requestAnimationFrame(loop);setTimeout(()=>{burst(W*.5,H*.3,140);boom()},150);setTimeout(()=>burst(W*.28,H*.43,100),600);setTimeout(()=>burst(W*.72,H*.4,105),900);setTimeout(()=>{burst(W*.5,H*.48,125);boom()},1200);setTimeout(()=>msg.classList.add("show"),1850);setTimeout(()=>{rocket(W*.2,H*.32,20);rocket(W*.8,H*.28,200)},2200);setTimeout(()=>{rocket(W*.35,H*.25,95);rocket(W*.65,H*.3,280)},2700)};